## Manipulação de Strings com Python 

> Uma variavel primeria de texto é chmada de char ou caracter possibilitando o armazenamento de 8 bit de memória. Quando necessitamos de um conjunto de caracteres utilizamos um objeto, ou variaveis compostas no caso da maioria das linguagens chamada de string. Vamo ver como se aplica.

In [7]:
frase = "Boa tarde a todos"
print(frase)
saudacao = frase[0:9]
print(saudacao)

Boa tarde a todos
Boa tarde


In [8]:
print(type(frase))
print(type(saudacao))


<class 'str'>
<class 'str'>


In [12]:
print(frase.count(' '))
print(saudacao.count(' '))


3
1


In [13]:
print(len(frase))
print(len(saudacao))

17
9


In [19]:
frase = frase.replace('a todos','galerinha!')
print(frase)
saudacao = saudacao.replace('tarde','noite')
print(saudacao)

Boa tarde galerinha
Boa noite


In [23]:
frase = [i for i in frase]
print(frase)

['B', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a']


In [21]:
for x in frase:
    print(x)

B
o
a
 
t
a
r
d
e
 
g
a
l
e
r
i
n
h
a


## Exercício 1
> Crie um código para a seguinte frase: "Sabia que o sabiá sabia assubiar?" reparticionando por espaços, após isso crie um print format para visualizar cada palavra em uma coluna separada

In [4]:
frase = "Sabia que o sabiá sabia assubiar"
palavras = frase.split()
print(palavras)

for i in range(max(len(x)for x in palavras)):
    for y in palavras:
        print(y[i] if i < len(y) else ' ', end =' ')

    print()


['Sabia', 'que', 'o', 'sabiá', 'sabia', 'assubiar']
S q o s s a 
a u   a a s 
b e   b b s 
i     i i u 
a     á a b 
          i 
          a 
          r 


In [21]:
for i in range(max(len(x) for x in palavras)):
    print(' '.join(x[i] if i < len(x) else ' ' for x in palavras))

S q o s s a
a u   a a s
b e   b b s
i     i i u
a     á a b
          i
          a
          r


## Introdução a Numpy

> Numpy é uma bibilioteca python para desenvolvimento de matrizes. Tem por objetivos facilitar na criação de algoritmos metemátiocos para solucionar paradgimas avançados em relação a arrays.

In [55]:

import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [28]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [31]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
print(a.max())
print(b.max())
print(c.max())
print(d.max())




3
6
1.0
1.0


In [41]:
print(a.min())
print(b.min())
print(c.min())
print(d.min())


1
1
1.0
0.0


In [42]:
print(a.sum())
print(b.sum())
print(c.sum())
print(d.sum())

6
21
9.0
5.0


> Para calcular média:

In [43]:
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())

2.0
3.5
1.0
0.2


> Para desvio padrão:

In [49]:
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))
print(round(d.std(),2))



0.82
1.71
0.0
0.4


## Exercício 2


> Crie uma matriz chamada contar com os numeros de 0 até 9. Ao final cire uma contagem, média e desvio padrão dessa matriz.Para adicionar de zero a 9 utilize for e depois atribua à matriz.

In [86]:
for x in range(0,10):
    contar = np.array([x])
    print(contar)
print(contar.mean())
print(round(contar.std(),2))


[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
9.0
0.0
